name: database_sqlite
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
